# 服务端口

#server:
#  port: 8004

# 应用名称及验证账号
spring:
  application:
    name: service-order
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 2000
    password:
    # 数据库连接配置
  datasource:
    # 配置当前使用的数据源的操作类型
    type: com.alibaba.druid.pool.DruidDataSource
    # 配置Mysql的驱动程序类型
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 数据库连接地址
    url: jdbc:myslq://localhost:3306/distributed-locl?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    # 数据库连接用户名
    username: root
    # 数据库连接秘钥
    password: 123456
    # 进行数据库连接池的配置
    dbcp2:
      # 初始化提供的连接数
      initial-size: 5
      # 数据库连接池的最小维持连接数
      min-idle: 5
      # 最大连接数
      max-total: 5
      # 等待连接获取的最大超时时间
      max-wait-millis: 200
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
# 自定义哨兵
sentinal:
  address:
    - 127.0.0.1:26379
    - 127.0.0.1:26479
    - 127.0.0.1:26579
  masterName: mymaster

# 注册中心
eureka:
  client:
    enabled: true
    # 设置服务注册中心的URL
    service-url:
      defaultZone: http://eureka-7900:7900/eureka/

#Mybatis 配置
mybatis:
  mapper-locations:
    - classpath:mapper/*.xml

---
spring:
  profiles: 8004
#服务端口
server:
  port: 8004

---
spring:
  profiles: 8005
#服务端口
server:
  port: 8005


